"""add url, short_link to cars

Revision ID: 6d77d4620e94
Revises: 2b262033582c
Create Date: 2024-03-10 08:55:55.428172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d77d4620e94'
down_revision = '2b262033582c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('short_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('short_link')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
